### ISSUE TITLE
Cannot connect to network with non-admin cardId on cloud

### ISSUE THREAD

**Issue by seond** [IBM/customer-loyalty-program#4]
The application is fully functional if use locally deployed network. When I tried deploying the network to cloud, the members/partners are created with no problem using admin card, however, I'm getting ECONNREFUSED error on logging in as a member/partner.

Here's the error log
```
memberData using param -  accountNumber: 000002 cardId: ACID000002
Error: Error trying login and get user Context. Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ECONNREFUSED 127.0.0.1:7054]
    at client.getUserContext.then.then.catch (/Users/seondongkim/Documents/Hyperledger/customer-loyalty-program/web-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:395:34)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: Error trying login and get user Context. Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ECONNREFUSED 127.0.0.1:7054]
    at client.getUserContext.then.then.catch (/Users/seondongkim/Documents/Hyperledger/customer-loyalty-program/web-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:395:34)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:30961) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Can't set headers after they are sent.
(node:30961) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

and here's the list of cards
```
Connection Profile: Alps Network - 8h5
┌──────────────────────────┬────────┬──────────────────┐
│ Card Name                │ UserId │ Business Network │
├──────────────────────────┼────────┼──────────────────┤
│ admin@Alps-Network---8h5 │ admin  │                  │
├──────────────────────────┼────────┼──────────────────┤
│ admin@clp-network        │ admin  │ clp-network      │
└──────────────────────────┴────────┴──────────────────┘


Connection Profile: hlfv1
┌────────────┬────────────┬──────────────────┐
│ Card Name  │ UserId     │ Business Network │
├────────────┼────────────┼──────────────────┤
│ ACID000001 │ ACID000001 │ clp-network      │
├────────────┼────────────┼──────────────────┤
│ ACID000002 │ ACID000002 │ clp-network      │
├────────────┼────────────┼──────────────────┤
│ ACID100001 │ ACID100001 │ clp-network      │
└────────────┴────────────┴──────────────────┘
```

I tried following the instruction precisely step-by-step but I'm not sure if I did wrong somewhere or this is how it is written. Thanks!

**Comment by raheelzubairy** [comment]
@SeonD Thank you for the feedback!  
There was an issue with the instruction which I have now updated #5 .  

The participant's identities need to use the connection profile from the IBM Blockchain Starter Plan - https://github.com/IBM/customer-loyalty-program/blob/master/docs/deploy-ibm-starter.md#configure-participants-connection-profile-for-ibm-blockchain-starter-plan-1

Please let us know if still any issues.
